# Generated by Django 4.1.7 on 2023-04-11 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ovo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                ("codigo", models.CharField(max_length=10, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("armazenado", "Armazenado"),
                            ("chocando", "Chocando"),
                        ],
                        default="armazenado",
                        max_length=20,
                    ),
                ),
                ("chocadeira", models.CharField(default=1, max_length=3)),
                ("data_chocadeira", models.DateField(blank=True, null=True)),
                ("dias_chocadeira", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Raca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
                (
                    "nome_cientifico",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pintinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("deficiencia", models.BooleanField(default=False)),
                ("data_eclosao", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "ovo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="granja.ovo"
                    ),
                ),
                (
                    "raca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="granja.raca"
                    ),
                ),
            ],
        ),
    ]
