# Generated by Django 4.1.7 on 2023-04-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("granja", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ovo",
            name="codigo",
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
