# Generated by Django 4.1.7 on 2023-04-13 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("granja", "0002_alter_ovo_codigo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pintinho",
            old_name="codigo",
            new_name="codigo_pintinho",
        ),
        migrations.RemoveField(
            model_name="pintinho",
            name="id",
        ),
        migrations.RemoveField(
            model_name="pintinho",
            name="ovo",
        ),
        migrations.AddField(
            model_name="pintinho",
            name="ovo_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="granja.ovo",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="GalinhaReprodutora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10)),
                ("piquete", models.IntegerField(blank=True, null=True)),
                (
                    "raca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="granja.raca"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ovo",
            name="galinha_reprodutora",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="granja.galinhareprodutora",
            ),
        ),
    ]
