# Generated by Django 4.1.7 on 2023-04-13 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("granja", "0004_alter_pintinho_codigo_pintinho"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pintinho",
            name="ovo_ptr",
        ),
        migrations.AddField(
            model_name="pintinho",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pintinho",
            name="ovo",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="granja.ovo"
            ),
            preserve_default=False,
        ),
    ]
